// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseVaultPath() {
  return window['go']['main']['ConfigService']['ChooseVaultPath']();
}

export function GetVaultPath() {
  return window['go']['main']['ConfigService']['GetVaultPath']();
}
