// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {index} from '../models';

export function QueryByType(arg1:string):Promise<Array<index.ObjectRow>>;
