// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function QueryByType(arg1) {
  return window['go']['main']['IndexService']['QueryByType'](arg1);
}
