// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vault} from '../models';

export function CreateFolder(arg1:string,arg2:string):Promise<string>;

export function CreateNote(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ReadNote(arg1:string):Promise<vault.Note>;

export function SaveNote(arg1:string,arg2:string):Promise<void>;

export function SaveNoteStructured(arg1:string,arg2:Record<string, any>,arg3:string):Promise<void>;

export function Tree():Promise<vault.Node>;
