// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['NotesService']['CreateFolder'](arg1, arg2);
}

export function CreateNote(arg1, arg2, arg3) {
  return window['go']['main']['NotesService']['CreateNote'](arg1, arg2, arg3);
}

export function ReadNote(arg1) {
  return window['go']['main']['NotesService']['ReadNote'](arg1);
}

export function SaveNote(arg1, arg2) {
  return window['go']['main']['NotesService']['SaveNote'](arg1, arg2);
}

export function SaveNoteStructured(arg1, arg2, arg3) {
  return window['go']['main']['NotesService']['SaveNoteStructured'](arg1, arg2, arg3);
}

export function Tree() {
  return window['go']['main']['NotesService']['Tree']();
}
