// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {schema} from '../models';

export function DeleteSchema(arg1:string):Promise<void>;

export function GetSchema(arg1:string):Promise<schema.Schema>;

export function ListKinds():Promise<Array<schema.KindMeta>>;

export function ListSchemas():Promise<Array<schema.LoadedSchema>>;

export function ResolveSchema(arg1:string):Promise<schema.Schema>;

export function SaveSchema(arg1:schema.Schema):Promise<void>;
