// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSchema(arg1) {
  return window['go']['main']['SchemaService']['DeleteSchema'](arg1);
}

export function GetSchema(arg1) {
  return window['go']['main']['SchemaService']['GetSchema'](arg1);
}

export function ListKinds() {
  return window['go']['main']['SchemaService']['ListKinds']();
}

export function ListSchemas() {
  return window['go']['main']['SchemaService']['ListSchemas']();
}

export function ResolveSchema(arg1) {
  return window['go']['main']['SchemaService']['ResolveSchema'](arg1);
}

export function SaveSchema(arg1) {
  return window['go']['main']['SchemaService']['SaveSchema'](arg1);
}
